### ISSUE TITLE
💥 monday 06.01.2020 masterplan 💥

### ISSUE THREAD

**Issue by schwittlick** [bgola/coding-dojo-gencomp-udk#3]
prep:
- bring more microphones (@bgola & beata)

monday:
- create a dojo timer w/ 8 led-lights (3min)
- more Tdefs for automatic movements
- touchosc interface for these tdefs
- setup one computer to run the installation mode
- figure out what the dojo performance is going to be about (e.g. 1 person playing sensors, 1 person live-coding)

**Comment by bgola** [comment]
some things made on monday:

- we created a template for sounds and controllers (check file under 2020/01/)
- template is able to use mic input or samples edited by pedro
- we jammed a bit with the template and each organized better the template

some decisions made on monday:

- soloists X soundscape: some people are playing soundscapes while one or two other are soloing
- mode for performance: moving head moves around until defining a spot somewhere where performers are. this defines the soloists X soundscapers. this happens every 3 minutes.
- @bgola will setup a raspberry pi to run the installation
- full setup on tuesday morning/afternoon.
- we all rehearse tuesday afternoon or wednesday morning/afternoon.
